import 'languages.g.dart';
export 'languages.g.dart';

class Language {
  const Language(this.isoCode, this.name, this.nativeName);

  final String name;
  final String isoCode;
  final String nativeName;

  Language.fromMap(Map<String, String> map)
      : name = map['name']!,
        isoCode = map['isoCode']!,
        nativeName = map['nativeName'] ?? map['name']!;

  /// Returns the Language matching the given ISO code from the standard list.
  factory Language.fromIsoCode(String isoCode) =>
      Languages.defaultLanguages.firstWhere((l) => l.isoCode == isoCode);

  bool operator ==(o) =>
      o is Language && name == o.name && isoCode == o.isoCode;

  @override
  int get hashCode => isoCode.hashCode;
}

final List defaultLanguagesList = [
  {"isoCode": "ab", "name": "Abkhazian", "nativeName": "Aҧсуа"},
  {"isoCode": "aa", "name": "Afar", "nativeName": "Afaraf"},
  {"isoCode": "af", "name": "Afrikaans", "nativeName": "Afrikaans"},
  {"isoCode": "ak", "name": "Akan", "nativeName": "Akan"},
  {"isoCode": "sq", "name": "Albanian", "nativeName": "Shqip"},
  {"isoCode": "am", "name": "Amharic", "nativeName": "አማርኛ"},
  {"isoCode": "ar", "name": "Arabic", "nativeName": "العربية"},
  {"isoCode": "an", "name": "Aragonese", "nativeName": "Aragonés"},
  {"isoCode": "hy", "name": "Armenian", "nativeName": "Հայերեն"},
  {"isoCode": "as", "name": "Assamese", "nativeName": "অসমীয়া"},
  {"isoCode": "av", "name": "Avaric", "nativeName": "Aвар мацӀ, магӀарул мацӀ"},
  {"isoCode": "ae", "name": "Avestan", "nativeName": "Avesta"},
  {"isoCode": "ay", "name": "Aymara", "nativeName": "Aymar aru"},
  {"isoCode": "az", "name": "Azerbaijani", "nativeName": "Azərbaycan dili"},
  {"isoCode": "bm", "name": "Bambara", "nativeName": "Bamanankan"},
  {"isoCode": "ba", "name": "Bashkir", "nativeName": "башҡорт теле"},
  {"isoCode": "eu", "name": "Basque", "nativeName": "Euskara, euskera"},
  {"isoCode": "be", "name": "Belarusian", "nativeName": "Беларуская"},
  {"isoCode": "bn", "name": "Bengali", "nativeName": "বাংলা"},
  {"isoCode": "bh", "name": "Bihari Languages", "nativeName": "भोजपुरी"},
  {"isoCode": "bi", "name": "Bislama", "nativeName": "Bislama"},
  {"isoCode": "nb", "name": "Norwegian", "nativeName": "Norsk bokmål"},
  {"isoCode": "bs", "name": "Bosnian", "nativeName": "Bosanski jezik"},
  {"isoCode": "br", "name": "Breton", "nativeName": "Brezhoneg"},
  {"isoCode": "bg", "name": "Bulgarian", "nativeName": "български език"},
  {"isoCode": "my", "name": "Burmese", "nativeName": "ဗမာစာ"},
  {"isoCode": "ca", "name": "Catalan", "nativeName": "Català"},
  {"isoCode": "km", "name": "Central Khmer", "nativeName": "ភាសាខ្មែរ"},
  {"isoCode": "ch", "name": "Chamorro", "nativeName": "Chamoru"},
  {"isoCode": "ce", "name": "Chechen", "nativeName": "нохчийн мотт"},
  {
    "isoCode": "ny",
    "name": "Chewa (Nyanja)",
    "nativeName": "chiCheŵa, chinyanja"
  },
  {"isoCode": "zh", "name": "Chinese", "nativeName": "中文 (Zhōngwén), 汉语, 漢語"},
  {"isoCode": "zh_Hans", "name": "Chinese (Simplified)", "nativeName": "简体中文"},
  {"isoCode": "zh_Hant", "name": "Chinese (Traditional)", "nativeName": "中國傳統"},
  {
    "isoCode": "cu",
    "name": "Church Slavonic",
    "nativeName": "ѩзыкъ словѣньскъ"
  },
  {"isoCode": "cv", "name": "Chuvash", "nativeName": "чӑваш чӗлхи"},
  {"isoCode": "kw", "name": "Cornish", "nativeName": "Kernewek"},
  {"isoCode": "co", "name": "Corsican", "nativeName": "Corsu, lingua corsa"},
  {"isoCode": "cr", "name": "Cree", "nativeName": "ᓀᐦᐃᔭᐍᐏᐣ"},
  {"isoCode": "hr", "name": "Croatian", "nativeName": "Hrvatski"},
  {"isoCode": "cs", "name": "Czech", "nativeName": "česky, čeština"},
  {"isoCode": "da", "name": "Danish", "nativeName": "Dansk"},
  {"isoCode": "dv", "name": "Dhivehi", "nativeName": "ދިވެހި"},
  {"isoCode": "nl", "name": "Dutch", "nativeName": "Nederlands, Vlaams"},
  {"isoCode": "dz", "name": "Dzongkha", "nativeName": "རྫོང་ཁ"},
  {"isoCode": "alpha2", "name": "English", "nativeName": "English"},
  {"isoCode": "en", "name": "English", "nativeName": "English"},
  {"isoCode": "eo", "name": "Esperanto", "nativeName": "Esperanto"},
  {"isoCode": "et", "name": "Estonian", "nativeName": "Eesti, eesti keel"},
  {"isoCode": "ee", "name": "Ewe", "nativeName": "Eʋegbe"},
  {"isoCode": "fo", "name": "Faroese", "nativeName": "Føroyskt"},
  {"isoCode": "fj", "name": "Fijian", "nativeName": "Vosa Vakaviti"},
  {"isoCode": "fi", "name": "Finnish", "nativeName": "Suomi, suomen kieli"},
  {
    "isoCode": "fr",
    "name": "French",
    "nativeName": "Français, langue française"
  },
  {"isoCode": "ff", "name": "Fulah", "nativeName": "Fulfulde, Pulaar, Pular"},
  {"isoCode": "gd", "name": "Gaelic", "nativeName": "Gàidhlig"},
  {"isoCode": "gl", "name": "Galician", "nativeName": "Galego"},
  {"isoCode": "lg", "name": "Ganda", "nativeName": "Luganda"},
  {"isoCode": "ka", "name": "Georgian", "nativeName": "ქართული"},
  {"isoCode": "de", "name": "German", "nativeName": "Deutsch"},
  {"isoCode": "el", "name": "Greek, Modern (1453-)", "nativeName": "Ελληνικά"},
  {"isoCode": "gn", "name": "Guarani", "nativeName": "Avañeẽ"},
  {"isoCode": "gu", "name": "Gujarati", "nativeName": "ગુજરાતી"},
  {"isoCode": "ht", "name": "Haitian", "nativeName": "Kreyòl ayisyen"},
  {"isoCode": "ha", "name": "Hausa", "nativeName": "Hausa, هَوُسَ"},
  {"isoCode": "he", "name": "Hebrew", "nativeName": "עברית"},
  {"isoCode": "hz", "name": "Herero", "nativeName": "Otjiherero"},
  {"isoCode": "hi", "name": "Hindi", "nativeName": "हिन्दी, हिंदी"},
  {"isoCode": "ho", "name": "Hiri Motu", "nativeName": "Hiri Motu"},
  {"isoCode": "hu", "name": "Hungarian", "nativeName": "Magyar"},
  {"isoCode": "is", "name": "Icelandic", "nativeName": "Íslenska"},
  {"isoCode": "io", "name": "Ido", "nativeName": "Ido"},
  {"isoCode": "ig", "name": "Igbo", "nativeName": "Asụsụ Igbo"},
  {"isoCode": "id", "name": "Indonesian", "nativeName": "Bahasa Indonesia"},
  {"isoCode": "ia", "name": "Interlingua", "nativeName": "Interlingua"},
  {"isoCode": "ie", "name": "Interlingue", "nativeName": "Interlingue"},
  {"isoCode": "iu", "name": "Inuktitut", "nativeName": "ᐃᓄᒃᑎᑐᑦ"},
  {"isoCode": "ik", "name": "Inupiaq", "nativeName": "Iñupiaq, Iñupiatun"},
  {"isoCode": "ga", "name": "Irish", "nativeName": "Gaeilge"},
  {"isoCode": "it", "name": "Italian", "nativeName": "Italiano"},
  {"isoCode": "ja", "name": "Japanese", "nativeName": "日本語 (にほんご／にっぽんご)"},
  {"isoCode": "jv", "name": "Javanese", "nativeName": "Basa Jawa"},
  {
    "isoCode": "kl",
    "name": "Kalaallisut",
    "nativeName": "kalaallisut, kalaallit oqaasii"
  },
  {"isoCode": "kn", "name": "Kannada", "nativeName": "ಕನ್ನಡ"},
  {"isoCode": "kr", "name": "Kanuri", "nativeName": "Kanuri"},
  {"isoCode": "ks", "name": "Kashmiri", "nativeName": "कश्मीरी, كشميري‎"},
  {"isoCode": "kk", "name": "Kazakh", "nativeName": "Қазақ тілі"},
  {"isoCode": "ki", "name": "Kikuyu", "nativeName": "Gĩkũyũ"},
  {"isoCode": "rw", "name": "Kinyarwanda", "nativeName": "Ikinyarwanda"},
  {"isoCode": "ky", "name": "Kirghiz", "nativeName": "кыргыз тили"},
  {"isoCode": "kv", "name": "Komi", "nativeName": "коми кыв"},
  {"isoCode": "kg", "name": "Kongo", "nativeName": "KiKongo"},
  {"isoCode": "ko", "name": "Korean", "nativeName": "한국어 (韓國語), 조선말 (朝鮮語)"},
  {"isoCode": "kj", "name": "Kuanyama", "nativeName": "Kuanyama"},
  {"isoCode": "ku", "name": "Kurdish", "nativeName": "Kurdî, كوردی‎"},
  {"isoCode": "lo", "name": "Lao", "nativeName": "ພາສາລາວ"},
  {"isoCode": "la", "name": "Latin", "nativeName": "latine, Lingua latina"},
  {"isoCode": "lv", "name": "Latvian", "nativeName": "Latviešu valoda"},
  {"isoCode": "li", "name": "Limburgan", "nativeName": "Limburgs"},
  {"isoCode": "ln", "name": "Lingala", "nativeName": "Lingála"},
  {"isoCode": "lt", "name": "Lithuanian", "nativeName": "lietuvių kalba"},
  {"isoCode": "lu", "name": "Luba-Katanga", "nativeName": "Luba-katanga"},
  {"isoCode": "lb", "name": "Luxembourgish", "nativeName": "Lëtzebuergesch"},
  {"isoCode": "mk", "name": "Macedonian", "nativeName": "македонски јазик"},
  {"isoCode": "mg", "name": "Malagasy", "nativeName": "Malagasy fiteny"},
  {
    "isoCode": "ms",
    "name": "Malay",
    "nativeName": "Bahasa Melayu, بهاس ملايو‎"
  },
  {"isoCode": "ml", "name": "Malayalam", "nativeName": "മലയാളം"},
  {"isoCode": "mt", "name": "Maltese", "nativeName": "Malti"},
  {"isoCode": "gv", "name": "Manx", "nativeName": "Gaelg, Gailck"},
  {"isoCode": "mi", "name": "Maori", "nativeName": "Te reo Māori"},
  {"isoCode": "mr", "name": "Marathi", "nativeName": "मराठी"},
  {"isoCode": "mh", "name": "Marshallese", "nativeName": "Kajin M̧ajeļ"},
  {"isoCode": "mn", "name": "Mongolian", "nativeName": "монгол"},
  {"isoCode": "na", "name": "Nauru", "nativeName": "Ekakairũ Naoero"},
  {"isoCode": "nv", "name": "Navajo", "nativeName": "Diné bizaad, Dinékʼehǰí"},
  {"isoCode": "nd", "name": "Ndebele, North", "nativeName": "IsiNdebele"},
  {"isoCode": "nr", "name": "Ndebele, South", "nativeName": "IsiNdebele"},
  {"isoCode": "ng", "name": "Ndonga", "nativeName": "Owambo"},
  {"isoCode": "ne", "name": "Nepali", "nativeName": "नेपाली"},
  {"isoCode": "se", "name": "Northern Sami", "nativeName": "Davvisámegiella"},
  {"isoCode": "no", "name": "Norwegian", "nativeName": "Norsk"},
  {"isoCode": "nn", "name": "Norwegian Nynorsk", "nativeName": "Norsk nynorsk"},
  {"isoCode": "oc", "name": "Occitan (post 1500)", "nativeName": "Occitan"},
  {"isoCode": "oj", "name": "Ojibwa", "nativeName": "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  {"isoCode": "or", "name": "Oriya", "nativeName": "ଓଡ଼ିଆ"},
  {"isoCode": "om", "name": "Oromo", "nativeName": "Afaan Oromoo"},
  {"isoCode": "os", "name": "Ossetian", "nativeName": "ирон æвзаг"},
  {"isoCode": "pi", "name": "Pali", "nativeName": "पाऴि"},
  {"isoCode": "pa", "name": "Panjabi", "nativeName": "ਪੰਜਾਬੀ, پنجابی‎"},
  {"isoCode": "fa", "name": "Persian", "nativeName": "فارسی"},
  {"isoCode": "pl", "name": "Polish", "nativeName": "Polski"},
  {"isoCode": "pt", "name": "Portuguese", "nativeName": "Português"},
  {"isoCode": "ps", "name": "Pushto", "nativeName": "پښتو"},
  {"isoCode": "qu", "name": "Quechua", "nativeName": "Runa Simi, Kichwa"},
  {"isoCode": "ro", "name": "Romanian", "nativeName": "Română"},
  {"isoCode": "rm", "name": "Romansh", "nativeName": "Rumantsch grischun"},
  {"isoCode": "rn", "name": "Rundi", "nativeName": "KiRundi"},
  {"isoCode": "ru", "name": "Russian", "nativeName": "русский язык"},
  {"isoCode": "sm", "name": "Samoan", "nativeName": "Gagana faa Samoa"},
  {"isoCode": "sg", "name": "Sango", "nativeName": "Yângâ tî sängö"},
  {"isoCode": "sa", "name": "Sanskrit", "nativeName": "संस्कृतम्"},
  {"isoCode": "sc", "name": "Sardinian", "nativeName": "sardu"},
  {"isoCode": "sr", "name": "Serbian", "nativeName": "Cрпски језик"},
  {"isoCode": "sn", "name": "Shona", "nativeName": "ChiShona"},
  {"isoCode": "ii", "name": "Sichuan Yi", "nativeName": "ꆈꌠꉙ"},
  {"isoCode": "sd", "name": "Sindhi", "nativeName": "सिन्धी, سنڌي، سندھی‎"},
  {"isoCode": "si", "name": "Sinhala", "nativeName": "සිංහල"},
  {"isoCode": "sk", "name": "Slovak", "nativeName": "Slovenčina"},
  {"isoCode": "sl", "name": "Slovenian", "nativeName": "Slovenščina"},
  {"isoCode": "so", "name": "Somali", "nativeName": "Soomaaliga, af Soomaali"},
  {"isoCode": "st", "name": "Sotho, Southern", "nativeName": "Sesotho"},
  {"isoCode": "es", "name": "Spanish", "nativeName": "Español, castellano"},
  {"isoCode": "su", "name": "Sundanese", "nativeName": "Basa Sunda"},
  {"isoCode": "sw", "name": "Swahili", "nativeName": "Kiswahili"},
  {"isoCode": "ss", "name": "Swati", "nativeName": "SiSwati"},
  {"isoCode": "sv", "name": "Swedish", "nativeName": "Svenska"},
  {
    "isoCode": "tl",
    "name": "Tagalog",
    "nativeName": "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"
  },
  {"isoCode": "ty", "name": "Tahitian", "nativeName": "Reo Tahiti"},
  {"isoCode": "tg", "name": "Tajik", "nativeName": "тоҷикӣ, toğikī, تاجیکی‎"},
  {"isoCode": "ta", "name": "Tamil", "nativeName": "தமிழ்"},
  {
    "isoCode": "tt",
    "name": "Tatar",
    "nativeName": "татарча, tatarça, تاتارچا‎"
  },
  {"isoCode": "te", "name": "Telugu", "nativeName": "తెలుగు"},
  {"isoCode": "th", "name": "Thai", "nativeName": "ไทย"},
  {"isoCode": "bo", "name": "Tibetan", "nativeName": "བོད་ཡིག"},
  {"isoCode": "ti", "name": "Tigrinya", "nativeName": "ትግርኛ"},
  {
    "isoCode": "to",
    "name": "Tonga (Tonga Islands)",
    "nativeName": "Faka Tonga"
  },
  {"isoCode": "ts", "name": "Tsonga", "nativeName": "Xitsonga"},
  {"isoCode": "tn", "name": "Tswana", "nativeName": "Setswana"},
  {"isoCode": "tr", "name": "Turkish", "nativeName": "Türkçe"},
  {"isoCode": "tk", "name": "Turkmen", "nativeName": "Türkmen, Түркмен"},
  {"isoCode": "tw", "name": "Twi", "nativeName": "Twi"},
  {"isoCode": "ug", "name": "Uighur", "nativeName": "Uyƣurqə, ئۇيغۇرچە‎"},
  {"isoCode": "uk", "name": "Ukrainian", "nativeName": "українська"},
  {"isoCode": "ur", "name": "Urdu", "nativeName": "اردو"},
  {"isoCode": "uz", "name": "Uzbek", "nativeName": "Zbek, Ўзбек, أۇزبېك‎"},
  {"isoCode": "ve", "name": "Venda", "nativeName": "Tshivenḓa"},
  {"isoCode": "vi", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
  {"isoCode": "vo", "name": "Volapük", "nativeName": "Volapük"},
  {"isoCode": "wa", "name": "Walloon", "nativeName": "Walon"},
  {"isoCode": "cy", "name": "Welsh", "nativeName": "Cymraeg"},
  {"isoCode": "fy", "name": "Western Frisian", "nativeName": "Frysk"},
  {"isoCode": "wo", "name": "Wolof", "nativeName": "Wollof"},
  {"isoCode": "xh", "name": "Xhosa", "nativeName": "IsiXhosa"},
  {"isoCode": "yi", "name": "Yiddish", "nativeName": "ייִדיש"},
  {"isoCode": "yo", "name": "Yoruba", "nativeName": "Yorùbá"},
  {"isoCode": "za", "name": "Zhuang", "nativeName": "Saɯ cueŋƅ, Saw cuengh"},
  {"isoCode": "zu", "name": "Zulu", "nativeName": "isiZulu"}
];
